version: '2'
services:

  web:
    image: ansible/awx_web:9.1.1
    container_name: awx_web
    depends_on:
      - rabbitmq
      - memcached
      - postgres
    ports:
      - "80:8052"
    hostname: awxweb
    user: root
    restart: unless-stopped
    volumes:
      - "/opt/awxcompose_9.1.1/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "/opt/awxcompose_9.1.1/environment.sh:/etc/tower/conf.d/environment.sh"
      - "/opt/awxcompose_9.1.1/credentials.py:/etc/tower/conf.d/credentials.py"
      - "/opt/awxcompose_9.1.1/nginx.conf:/etc/nginx/nginx.conf:ro"
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 

  task:
    image: ansible/awx_task:9.1.1
    container_name: awx_task
    depends_on:
      - rabbitmq
      - memcached
      - web
      - postgres
    hostname: awx
    user: root
    restart: unless-stopped
    volumes:
      - "/opt/awxcompose_9.1.1/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "/opt/awxcompose_9.1.1/environment.sh:/etc/tower/conf.d/environment.sh"
      - "/opt/awxcompose_9.1.1/credentials.py:/etc/tower/conf.d/credentials.py"
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 

  rabbitmq:
    image: ansible/awx_rabbitmq:3.7.4
    container_name: awx_rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_VHOST: "awx"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "awxpass"
      RABBITMQ_ERLANG_COOKIE: cookiemonster
      http_proxy: 
      https_proxy: 
      no_proxy: 

  memcached:
    image: "memcached:alpine"
    container_name: awx_memcached
    restart: unless-stopped
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 

  postgres:
    image: postgres:10
    container_name: awx_postgres
    restart: unless-stopped
    volumes:
      - /opt/awxdb_9.1.1/10/data/:/var/lib/postgresql/data/pgdata:Z
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: awxpass
      POSTGRES_DB: awx
      PGDATA: /var/lib/postgresql/data/pgdata
      http_proxy: 
      https_proxy: 
      no_proxy: 
