version: '2'
services:

  web:
    image: ansible/awx_web:10.0.0
    container_name: awx_web
    depends_on:
      - redis
      - memcached
      - postgres
    ports:
      - "80:8052"
    hostname: awxweb
    user: root
    restart: unless-stopped
    volumes:
      - "/opt/awxcompose_10.0.0/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "/opt/awxcompose_10.0.0/environment.sh:/etc/tower/conf.d/environment.sh"
      - "/opt/awxcompose_10.0.0/credentials.py:/etc/tower/conf.d/credentials.py"
      - "/opt/awxcompose_10.0.0/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "/opt/awxcompose_10.0.0/redis_socket:/var/run/redis/:rw"
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 

  task:
    image: ansible/awx_task:10.0.0
    container_name: awx_task
    depends_on:
      - redis
      - memcached
      - web
      - postgres
    hostname: awx
    user: root
    restart: unless-stopped
    volumes:
      - "/opt/awxcompose_10.0.0/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "/opt/awxcompose_10.0.0/environment.sh:/etc/tower/conf.d/environment.sh"
      - "/opt/awxcompose_10.0.0/credentials.py:/etc/tower/conf.d/credentials.py"
      - "/opt/awxcompose_10.0.0/redis_socket:/var/run/redis/:rw"
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 

  redis:
    image: redis
    container_name: awx_redis
    restart: unless-stopped
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 
    command: ["/usr/local/etc/redis/redis.conf"]
    volumes:
      - "/opt/awxcompose_10.0.0/redis.conf:/usr/local/etc/redis/redis.conf:ro"
      - "/opt/awxcompose_10.0.0/redis_socket:/var/run/redis/:rw"

  memcached:
    image: "memcached:alpine"
    container_name: awx_memcached
    restart: unless-stopped
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 

  postgres:
    image: postgres:10
    container_name: awx_postgres
    restart: unless-stopped
    volumes:
      - /opt/awxdb_10.0.0/10/data/:/var/lib/postgresql/data/pgdata:Z
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: awxpass
      POSTGRES_DB: awx
      PGDATA: /var/lib/postgresql/data/pgdata
      http_proxy: 
      https_proxy: 
      no_proxy: 
